import { ActionID as ActionIdProto } from '/wotlk/core/proto/common.js';
import { ResourceType } from '/wotlk/core/proto/api.js';
import { Item } from '/wotlk/core/proto/common.js';
import { OtherAction } from '/wotlk/core/proto/common.js';
export declare const USE_WOTLK_DB = false;
export declare class ActionId {
    readonly itemId: number;
    readonly spellId: number;
    readonly otherId: OtherAction;
    readonly tag: number;
    readonly baseName: string;
    readonly name: string;
    readonly iconUrl: string;
    private constructor();
    anyId(): number;
    equals(other: ActionId): boolean;
    equalsIgnoringTag(other: ActionId): boolean;
    setBackground(elem: HTMLElement): void;
    static makeItemUrl(id: number): string;
    static makeSpellUrl(id: number): string;
    setWowheadHref(elem: HTMLAnchorElement): void;
    setBackgroundAndHref(elem: HTMLAnchorElement): void;
    fillAndSet(elem: HTMLAnchorElement, setHref: boolean, setBackground: boolean): Promise<ActionId>;
    fill(playerIndex?: number): Promise<ActionId>;
    toString(): string;
    toStringIgnoringTag(): string;
    toProto(): ActionIdProto;
    toProtoString(): string;
    withoutTag(): ActionId;
    static fromEmpty(): ActionId;
    static fromItemId(itemId: number, tag?: number): ActionId;
    static fromSpellId(spellId: number, tag?: number): ActionId;
    static fromOtherId(otherId: OtherAction, tag?: number): ActionId;
    static fromPetName(petName: string): ActionId;
    static fromItem(item: Item): ActionId;
    static fromProto(protoId: ActionIdProto): ActionId;
    static fromLogString(str: string): ActionId;
    private static makeIconUrl;
    private static dbCache;
    private static getDb;
    private static getDbTooltipDataHelper;
    private static getWowheadTooltipDataHelper;
    private static getWotlkdbTooltipDataHelper;
    static getItemTooltipData(id: number): Promise<any>;
    static getSpellTooltipData(id: number): Promise<any>;
    static getTooltipData(actionId: ActionId): Promise<any>;
}
export declare const defaultTargetIcon = "https://wow.zamimg.com/images/wow/icons/large/spell_shadow_metamorphosis.jpg";
export declare const resourceTypeToIcon: Record<ResourceType, string>;
