import { Player } from '/wotlk/core/player.js';
import { Class } from '/wotlk/core/proto/common.js';
import { Spec } from '/wotlk/core/proto/common.js';
import { SpecTalents } from '/wotlk/core/proto_utils/utils.js';
import { TalentsConfig, TalentsPicker } from './talents_picker.js';
import { GlyphsPicker } from './glyphs_picker.js';
export declare function newTalentsPicker(parent: HTMLElement, player: Player<any>): TalentsPicker<Player<any>, any>;
export declare function newGlyphsPicker(parent: HTMLElement, player: Player<any>): GlyphsPicker;
export declare function talentSpellIdsToTalentString(playerClass: Class, talentIds: Array<number>): string;
export declare function playerTalentStringToProto<SpecType extends Spec>(spec: Spec, talentString: string): SpecTalents<SpecType>;
export declare function talentStringToProto<TalentsProto>(proto: TalentsProto, talentString: string, talentsConfig: TalentsConfig<TalentsProto>): TalentsProto;
export declare function protoToTalentString<TalentsProto>(proto: TalentsProto, talentsConfig: TalentsConfig<TalentsProto>): string;
