import { BattleElixir } from '/wotlk/core/proto/common.js';
import { Explosive } from '/wotlk/core/proto/common.js';
import { Flask } from '/wotlk/core/proto/common.js';
import { Food } from '/wotlk/core/proto/common.js';
import { GuardianElixir } from '/wotlk/core/proto/common.js';
import { Conjured } from '/wotlk/core/proto/common.js';
import { Potions } from '/wotlk/core/proto/common.js';
import { WeaponImbue } from '/wotlk/core/proto/common.js';
import { Player } from '/wotlk/core/player.js';
import { IconPickerConfig } from './icon_picker.js';
import { IconEnumPickerConfig } from './icon_enum_picker.js';
import { MultiIconPickerConfig } from './multi_icon_picker.js';
export declare const AllStatsBuff: MultiIconPickerConfig<Player<any>>;
export declare const AllStatsPercentBuff: MultiIconPickerConfig<Player<any>>;
export declare const ArmorBuff: MultiIconPickerConfig<Player<any>>;
export declare const StaminaBuff: MultiIconPickerConfig<Player<any>>;
export declare const StrengthAndAgilityBuff: MultiIconPickerConfig<Player<any>>;
export declare const IntellectBuff: MultiIconPickerConfig<Player<any>>;
export declare const SpiritBuff: MultiIconPickerConfig<Player<any>>;
export declare const AttackPowerBuff: MultiIconPickerConfig<Player<any>>;
export declare const AttackPowerPercentBuff: MultiIconPickerConfig<Player<any>>;
export declare const DamagePercentBuff: MultiIconPickerConfig<Player<any>>;
export declare const DamageReductionPercentBuff: MultiIconPickerConfig<Player<any>>;
export declare const HastePercentBuff: MultiIconPickerConfig<Player<any>>;
export declare const HealthBuff: MultiIconPickerConfig<Player<any>>;
export declare const MP5Buff: MultiIconPickerConfig<Player<any>>;
export declare const MeleeCritBuff: MultiIconPickerConfig<Player<any>>;
export declare const MeleeHasteBuff: MultiIconPickerConfig<Player<any>>;
export declare const ReplenishmentBuff: MultiIconPickerConfig<Player<any>>;
export declare const SpellCritBuff: MultiIconPickerConfig<Player<any>>;
export declare const SpellHasteBuff: MultiIconPickerConfig<Player<any>>;
export declare const SpellPowerBuff: MultiIconPickerConfig<Player<any>>;
export declare const Bloodlust: IconPickerConfig<Player<any>, boolean>;
export declare const RetributionAura: IconPickerConfig<Player<any>, boolean>;
export declare const ShadowProtection: IconPickerConfig<Player<any>, boolean>;
export declare const BraidedEterniumChain: IconPickerConfig<Player<any>, boolean>;
export declare const ChainOfTheTwilightOwl: IconPickerConfig<Player<any>, boolean>;
export declare const HeroicPresence: IconPickerConfig<Player<any>, boolean>;
export declare const EyeOfTheNight: IconPickerConfig<Player<any>, boolean>;
export declare const Thorns: IconPickerConfig<Player<any>, number>;
export declare const ManaTideTotem: IconPickerConfig<Player<any>, number>;
export declare const Innervate: IconPickerConfig<Player<any>, number>;
export declare const PowerInfusion: IconPickerConfig<Player<any>, number>;
export declare const MajorArmorDebuff: MultiIconPickerConfig<Player<any>>;
export declare const MinorArmorDebuff: MultiIconPickerConfig<Player<any>>;
export declare const AttackPowerDebuff: MultiIconPickerConfig<Player<any>>;
export declare const BleedDebuff: MultiIconPickerConfig<Player<any>>;
export declare const CritDebuff: MultiIconPickerConfig<Player<any>>;
export declare const MeleeAttackSpeedDebuff: MultiIconPickerConfig<Player<any>>;
export declare const MeleeHitDebuff: MultiIconPickerConfig<Player<any>>;
export declare const PhysicalDamageDebuff: MultiIconPickerConfig<Player<any>>;
export declare const SpellCritDebuff: MultiIconPickerConfig<Player<any>>;
export declare const SpellHitDebuff: MultiIconPickerConfig<Player<any>>;
export declare const SpellDamageDebuff: MultiIconPickerConfig<Player<any>>;
export declare const JudgementOfWisdom: IconPickerConfig<Player<any>, boolean>;
export declare const JudgementOfLight: IconPickerConfig<Player<any>, boolean>;
export declare const GiftOfArthas: IconPickerConfig<Player<any>, boolean>;
export declare const SuperSapper: IconPickerConfig<Player<any>, boolean>;
export declare const GoblinSapper: IconPickerConfig<Player<any>, boolean>;
export declare const SpicedMammothTreats: IconPickerConfig<Player<any>, boolean>;
export declare const PetScrollOfAgilityV: IconPickerConfig<Player<any>, boolean>;
export declare const PetScrollOfStrengthV: IconPickerConfig<Player<any>, boolean>;
export declare function makeMultiIconInput<ModObject>(inputs: Array<IconPickerConfig<ModObject, any>>, label: string): MultiIconPickerConfig<ModObject>;
export declare const makePotionsInput: (options: Potions[]) => IconEnumPickerConfig<Player<any>, Potions>;
export declare const makeConjuredInput: (options: Conjured[]) => IconEnumPickerConfig<Player<any>, Conjured>;
export declare const makeFlasksInput: (options: Flask[]) => IconEnumPickerConfig<Player<any>, Flask>;
export declare const makeBattleElixirsInput: (options: BattleElixir[]) => IconEnumPickerConfig<Player<any>, BattleElixir>;
export declare const makeGuardianElixirsInput: (options: GuardianElixir[]) => IconEnumPickerConfig<Player<any>, GuardianElixir>;
export declare const makeFoodInput: (options: Food[]) => IconEnumPickerConfig<Player<any>, Food>;
export declare const FillerExplosiveInput: IconEnumPickerConfig<Player<any>, Explosive>;
export declare function makeWeaponImbueInput(isMainHand: boolean, options: Array<WeaponImbue>): IconEnumPickerConfig<Player<any>, WeaponImbue>;
